### ISSUE TITLE
Enable other issues type

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/.github#3]
https://github.com/developmentseed/.github/blob/db02c2bf9ad610b8061de8c85d402b88a7ae20a1/.github/ISSUE_TEMPLATE/issue-1.md?plain=1#L7

with ☝️ when we try to open an issue in a repo we get 👇 

<img width="1079" alt="Screenshot 2023-04-21 at 2 30 01 PM" src="https://user-images.githubusercontent.com/10407788/233636144-4a5bc6d9-9074-445d-8100-be08240725e6.png">

**Comment by vincentsarago** [comment]
🤦 
![image](https://user-images.githubusercontent.com/10407788/233637153-75f90848-2339-40eb-a2b3-3a5fb61eab91.png)

You can open a blanck issue but It's a bit confusing. 

I would personally prefer we add other generic types 🤷

**Comment by geohacker** [comment]
This is done https://github.com/developmentseed/.github/blob/main/.github/ISSUE_TEMPLATE/blank-issue.md
